import type { Metadata } from "next";
import localFont from "next/font/local";
import { Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/app/providers";

const alpino = localFont({
  src: [
    {
      path: "../public/fonts/alpino/Alpino-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/alpino/Alpino-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/alpino/Alpino-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/alpino/Alpino-Black.woff2",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-alpino",
  display: "swap",
});

const sentient = localFont({
  src: [
    {
      path: "../public/fonts/sentient/Sentient-Italic.woff2",
      weight: "400",
      style: "italic",
    },
  ],
  variable: "--font-sentient",
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${alpino.variable} ${sentient.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
